### ISSUE TITLE
Problem when starting readyset with mysql

### ISSUE THREAD

**Issue by Lordworms** [readysettech/readyset#1000]
**Describe the problem**
I have a MySQL server run in port 3306 of my cloud machine but when I run the scripts like 
```
cargo run --bin readyset-server -- --upstream-db-url mysql://yanxinxiang:123456@127.1/test --deployment test
```
it generates an error like this 
<img width="1119" alt="image" src="https://github.com/readysettech/readyset/assets/48054792/9e393021-0d25-4519-b367-f283004c5495">
Since I am not that familiar with the controller code, I find the problem lies in the leadership election function.
my problem is
I. How to fix it?
II. how does the election process go, like a raft process?

**Comment by Lordworms** [comment]
I changed to directly start with the binary in /target instead of using cargo run, it starts fine, what's the difference between directly run it and using cargo run?
<img width="1118" alt="image" src="https://github.com/readysettech/readyset/assets/48054792/806be716-3108-41a9-97cd-78dccaf52997">

**Comment by aglover** [comment]
Thank you @Lordworms! In the latter case, you're running ReadySet in standalone mode (which is the preferred means to run the process). The former errors are from an attempt to run in a multi-process mode. We should make that more clear in our documentation! I'm going to close this issue after creating a ticket to clarify things. THANK YOU!
