### ISSUE TITLE
There are no networking errors

### ISSUE THREAD

**Issue by gyp8735abc** [readysettech/readyset#12]
![image](https://user-images.githubusercontent.com/13816018/177508842-784cb370-9a26-4325-bf3a-c58f0f45c096.png)

**Comment by gyp8735abc** [comment]
> It looks like you didn't launch consul? Are you trying to only launch the readyset-server container and nothing else?

Yes, there is no network on this server, I want to start this service on the Intranet, is that ok? Is there any configuration file of Docker-compose for reference? Thank you.

**Comment by glittershark** [comment]
@gyp8735abc: There's an [example `docker-compose.yml` in the root of the repository](https://github.com/readysettech/readyset/blob/main/docker-compose.yml) and an [example override file to expose required ports](https://github.com/readysettech/readyset/blob/main/docker-compose.override.yml.example). There's some documentation on the usage of those [in `development.md`](https://github.com/readysettech/readyset/blob/main/development.md#runtime-dependencies-upstream-database-and-consul). Also, probably the easiest way to get up and running with a ReadySet cluster is to use the orchestrator, which you can run via `bash -c "$(curl -sSL https://launch.readyset.io)"`

**Comment by PrismaPhonic** [comment]
Marking this as closed for now as I believe this is a non-issue.
