### ISSUE TITLE
readyset only support mysql 8+, can NOT support 5.7?

### ISSUE THREAD

**Issue by shawn0915** [readysettech/readyset#124]
**Describe the problem**
Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**
What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up ReadySet with docker
2. connect db via readyset
3. but get this info

```
$ mysql -uroot -P3307 -h127.0.0.1
ERROR 1105 (HY000): #HY000Error connecting to upstream database: Upstream server version 5-7 is too low. Minimum supported major version is 8
```

**Expected behavior**

just wanna confirm, does readyset only support mysql 8+?

**Comment by glittershark** [comment]
@shawn0915 that's correct, ReadySet only currently supports MySQL 8. I'm not sure all of what'd be required to support MySQL 5.7, but at the very least there are significant differences in the semantics of SQL expressions, especially with respect to collations.

**Comment by shawn0915** [comment]
@glittershark noted, really thank u for such quick response.
