### ISSUE TITLE
Unify experimental features parameter and ENV naming convention

### ISSUE THREAD

**Issue by altmannmarcelo** [readysettech/readyset#1339]
**Description**

Readyset support some experimental features, that are not enabled by default. The current list is [https://github.com/readysettech/readyset/blob/stable-240627/readyset-server/src/lib.rs#L611-L636](https://github.com/readysettech/readyset/blob/stable-240627/readyset-server/src/lib.rs#L611-L636)

Take for example straddle joins:

```
/// Enable experimental support for straddled joins (joins with partial keys traced to both
/// parents)
#[arg(long, env = "EXPERIMENTAL_STRADDLED_JOIN_SUPPORT", hide = true)]
pub enable_experimental_straddled_joins: bool,
```

this if used with a parameter, starts with `enable` and uses the word `joins` plural, if used as an ENV variable, this does not contain the word `enable` it uses the word `join` singular and has a `_support` in the end.

This is a problem because:

* if we pass this as a parameter, it will complain if the parameter does not exists, however, if we are using readyset as a service, it uses the ENV and you will not know that you are using a wrong parameter until you try to cache a query that needs support for whatever you are trying to enable.
* Currently changing those configurations require to re-create the whole readyset installation, meaning a new snapshot will take place

**Change in user-visible behavior**

**Requires documentation change**

**Comment by davisjc** [comment]
This is fixed in 292d031.
