### ISSUE TITLE
I'm not sure if it run successfully ，in docker

### ISSUE THREAD

**Issue by BroadZhang** [readysettech/readyset#1360]
![image](https://github.com/user-attachments/assets/5e4da8c9-73f3-4a86-8f97-e70d2d15f4c3)

I run it through a Docker image, but I'm not sure if it was successful because I didn't see the display "**INFO replicators:: noria'apter: Streaming replication started**" mentioned in the documentation，No errors were displayed。

And I can't connect through MySQL shell, I don't know where the problem lies
![image](https://github.com/user-attachments/assets/5f7de533-d293-4e4c-8fa3-88580b9179b6)

**Comment by altmannmarcelo** [comment]
Hi @BroadZhang ,

Thanks for your request. By looking into your screenshot, Readyset was started successfully. 
From your error, it looks like you are trying to connect with an user `ODBC` while Readyset is configured to use the user `root`

Can you try:

```
mysql -u root -p -h 192.168.204.10 -P 3307
```
And enter the root password?

**Comment by BroadZhang** [comment]
I interpretive error. Logging in with the username and password from the database was successful. Thank you
