### ISSUE TITLE
Panic with `LITERAL != COLUMN`

### ISSUE THREAD

**Issue by jscheid** [readysettech/readyset#1391]
**Describe the problem**

```sql
psql> CREATE CACHE FROM SELECT SUM(val) FROM m WHERE 123 != foo_id;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

**To Reproduce**

See above. I don't think any special table layout is necessary to reproduce but let me know if you need more information.

**Expected behavior**

Should work as `foo_id != 123` does, or as `123 = foo_id` does.

**Additional data / screenshots**

See [full backtrace](https://gist.github.com/jscheid/0db48b81d844635ba057d324c8e8b80a)

**Environment**
 - ReadySet version [e.g., beta-2022-11-02]: `stable-240919`
 - ReadySet deployment method [e.g, local orchestrator, Helm chart, binaries]: binary built from source
 - Upstream database and version [e.g., Postgres 14]: Postgres 14
 - Client app [e.g., `psql`, `mysql`, SQLAlchemy, TypeORM]: `psql`

**Additional context**

[Famous last words?](https://github.com/readysettech/readyset/blob/4c742b9ad5573dadc9236dfd5f558bd9b5dd101a/readyset-sql-passes/src/adapter_rewrites/autoparameterize.rs#L219-L221) 😺

**Comment by gvsg-rs** [comment]
We did not in fact check 'op.is_ordering_comparison()' in this code path. Thank you for the report!

**Comment by vassili-zarouba** [comment]
The issue has been fixed and merged into main branch.
