### ISSUE TITLE
Bug: Error with enum type and geography type at Postgres

### ISSUE THREAD

**Issue by bungambohlah** [readysettech/readyset#14]
So, i just install ReadySet at my local with my Postgres 14 existing.

Then, i just want to select my "Table" with specific type like `enum` or `geography`.
When i try to query got this error.

```
ERROR:  internal error: could not retrieve expected column index 3 from row while parsing psql result: error deserializing column 3: cannot convert between the Rust type `noria_data::DataType` and the Postgres type `geography`
```

this is bug? or i just wrong install

btw, great work for doing this. Keep it up.

**Comment by bungambohlah** [comment]
Someone just already drop this same problem and got answer for that, because ReadySet got limited supported types. So, this need to explain at the docs.
Thank you and keep the good work.

**Comment by bungambohlah** [comment]
The limited types list:

ReadySet supports the following data types:

* BOOL
* CHAR
* VARCHAR
* INT
* INT UNSIGNED
* BIGINT
* BIGINT UNSIGNED
* SMALLINT
* SMALLINT UNSIGNED
* BLOB
* LONGBLOG
* MEDIUMBLOB
* TINYBLOB
* DOUBLE
* FLOAT
* REAL
* NUMERIC
* TINYTEXT
* MEDIUMTEXT
* LONGTEXT
* TEXT
* DATE
* DATETIME 
* TIME
* TIMESTAMP / TIMESTAMP WITHOUT TIME ZONE
* TIMESTAMPTZ / TIMESTAMP WITH TIME ZONE
* BINARY
* VARBINARY
* DECIMAL
* BYTEARRAY
* BIT
* VARBIT 
* SERIAL
* BIGSERIAL

ReadySet additionally has limited support for the following data types:

* JSON
* JSONB
* UUID
* MACADDR
* INET

**Comment by glittershark** [comment]
@bungambohlah the full list of supported types (and everything else query-support related) is now up at https://docs.readyset.io/using/queries#types

**Comment by bungambohlah** [comment]
@glittershark ok noted that, thank you for the updates
