### ISSUE TITLE
testing: Confirm any Aurora PG role with `rds_superuser` is sufficient for ReadySet

### ISSUE THREAD

**Issue by jasobrown-rs** [readysettech/readyset#161]
The master account for Aurora PG will be assigned `rds_superuser`\[0\], but users might not want to use that account for readyset. Hence we should check that other user roles, when used for the readyset user, can perform all the appropriate ReadySet behaviors, such as DDL trigger creates.

\[0\] [AWS Aurora PG roles docs](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Appendix.PostgreSQL.CommonDBATasks.Roles.html#Appendix.PostgreSQL.CommonDBATasks.Roles.rds_superuser)

**Comment by jasobrown-rs** [comment]
Also, we might need to verify on different, supported versions of PG (iirc, there was a difference between PG 14 and lower)

**Comment by amartin96** [comment]
Confirmed that any role that is a member of `rds_superuser` can successfully create triggers and replicate from a newly created Aurora Postgres instance.

Versions tested:

* 13\.11
* 14\.6

Procedure:

* Create an aurora instance
* Shell into it and run the following:

```
CREATE ROLE myrole WITH LOGIN PASSWORD 'password';
GRANT rds_superuser TO myrole;
```

* Start ReadySet using the newly created role
