### ISSUE TITLE
Docs: running ReadySet with proper SSL certs for Aurora databases

### ISSUE THREAD

**Issue by jasobrown-rs** [readysettech/readyset#162]
Add instructions to our public-facing doucmentation on how to properly/correctly configure SSL/TLS certs for connecting to AWS Aurora. There's both the cert installation part (which is good for our own internal use), as well as how to configure ReadySet (if anything special is required).

**Comment by amartin96** [comment]
Importing TLS certificate in macos:

* Download the RDS global certificate bundle [https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem](https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem)
  * alternatively, only download the region-specific bundle(s) you need: [https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html#UsingWithRDS.SSL.RegionCertificates](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html#UsingWithRDS.SSL.RegionCertificates)
* Open the `Keychain Access` application
* From the left-side menu, under `System Keychains`, select `System`
* Drag and drop the certificate bundle into the keychain (or `file`→`Import items…`)
* Open the `Amazon RDS Root 2019 CA` certificate
* Set `Trust` → `Secure Sockets Layer (SSL)` to `Always Trust` and close the window (it prompts for auth)

**Comment by jasobrown-rs** [comment]
Ahh, cool. That is handy for those running on their local macOS laptop. Should we add help for linux? (I'm not too worried about Windows :P )

**Comment by amartin96** [comment]
Definitely! I'm continuing to look into this. There's a couple of points of friction:

* `Amazon RDS Root 2019 CA` expires in 2024. The newer certs that Amazon recommends are also in that bundle, but I haven't yet gotten `Keychain Access` to recognize them.
* `readyset` has the `--ssl-root-cert` option, but I haven't yet gotten it to work with the RDS certs. If this ultimately works, its simpler than maintaining per-OS cert installation instructions.

**Comment by amartin96** [comment]
`--ssl-root-cert` accepts a path to a single PEM (base64) or DER (binary) x509 certificate. The RDS cert bundle is a list of many PEM certs, which the `native-tls` package doesn't parse. If you extract the first cert from the bundle into its own `.pem` file, it works, but only on Ubuntu (and presumably other Linux distros). On macos, it still fails because the cert is not trusted.

**Comment by amartin96** [comment]
[https://github.com/readysettech/docs/pull/57](https://github.com/readysettech/docs/pull/57)
