### ISSUE TITLE
Column list in cache is stale even after dropping and recreating the cache

### ISSUE THREAD

**Issue by ethan-readyset** [readysettech/readyset#173]
### Description

The change introduced in [this CL](https://gerrit.readyset.name/c/readyset/+/5608/17) causes [this test](https://github.com/readysettech/readyset/blob/main/replicators/tests/tests.rs#L1387) to fail at [this line](https://github.com/readysettech/readyset/blob/beta-2023-07-26/replicators/tests/tests.rs#L1387%5C) because the view seems to be missing a column. Adding a 1-second sleep directly before that line seems to fix the issue. The `check_results` function queries the cache 40 times with 500ms sleeps between each query until the results match, so it's not clear why adding the 1-second sleep helps. What's even more strange is that if a sleep is added before [this line](https://github.com/readysettech/readyset/blob/b9335f9bffbb6f7eb4f885a36d0c4b2a2a7d298e/replicators/tests/tests.rs#L389), the tests pass, but if a sleep is added before [this line](https://github.com/readysettech/readyset/blob/b9335f9bffbb6f7eb4f885a36d0c4b2a2a7d298e/replicators/tests/tests.rs#L418), the tests fail. It's almost like if we create the cache once with the stale data, the cache never contains the correct data thereafter, even after being dropped and recreated.

Graph from test without sleep (failing test):

![graph_without_sleep.png](https://uploads.linear.app/76d4be3b-10f5-452e-a0bd-5ce299bfcdf4/bdd0ef9e-808b-4f0a-ae11-454a28b2fffb/288a32d9-b3d4-4596-be9e-e1cb66a7c164?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzc2ZDRiZTNiLTEwZjUtNDUyZS1hMGJkLTVjZTI5OWJmY2RmNC9iZGQwZWY5ZS04MDhiLTRmMGEtYWUxMS00NTRhMjhiMmZmZmIvMjg4YTMyZDktYjNkNC00NTk2LWJlOWUtZTFjYjY2YTdjMTY0IiwiaWF0IjoxNjkxNjA2MDg2LCJleHAiOjE2OTE2OTI0ODZ9.xh-0Iyw26sm8ZCxpbJrkR3jwmrSnQrlaE3ylWuoeF88)

Graph from test with sleep (passing test):

![graph_with_sleep.png](https://uploads.linear.app/76d4be3b-10f5-452e-a0bd-5ce299bfcdf4/746037bb-c1c6-492d-b15d-3c6ce1c378d0/1240e7cb-60f5-4e9c-89ae-e6ebfe74fee9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzc2ZDRiZTNiLTEwZjUtNDUyZS1hMGJkLTVjZTI5OWJmY2RmNC83NDYwMzdiYi1jMWM2LTQ5MmQtYjE1ZC0zYzZjZTFjMzc4ZDAvMTI0MGU3Y2ItNjBmNS00ZTljLTg5YWUtZTZlYmZlNzRmZWU5IiwiaWF0IjoxNjkxNjA2MDg2LCJleHAiOjE2OTE2OTI0ODZ9.HhN_FB4Ms8lyNGApL_cwS4k49mAr8jR4Ozhx5tc4KsA)

The above graphviz dumps show that the view in question (`repl2_view`) is missing a column in the failing test (the one without the sleep). So far, the working theory is that there may be a race condition where we are getting the old view as part of the migration before the old view is dropped. It seems like the CL linked above just changes the timing of events in the system, triggering the race condition; it doesn't seem like the CL introduces a new regression.

Relevant Slack thread: [https://readyset-workspace.slack.com/archives/C01HF1WTP6Y/p1691589973142429](https://readyset-workspace.slack.com/archives/C01HF1WTP6Y/p1691589973142429)

### Expected behavior

When the view is dropped and recreated, it should reflect the most up-to-date schema of the base table.

### Actual behavior

When the view is dropped and recreated, the schema is incorrect.

### Steps to reproduce

Run [this test](https://github.com/readysettech/readyset/blob/beta-2023-07-26/replicators/tests/tests.rs#L666) without the sleep.

### Upstream DB type and version

```
 PostgreSQL 14.6 (Debian 14.6-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
```

### Instance Details

N/A

### Deployment Details

Binary built from latest commit and run outside of docker

macOS 13.4.1 (c) (22F770820d)

### Logs

N/A

**Comment by glittershark** [comment]
I think I might know what's happening here - those replicators tests query from a SQL VIEW, not the table directly, but that view isn't recreated within the loop - I'd bet we're running desugaring rewrite passes (notably `star_expansion`, here) on `VIEW`s once, and not re-running them when the tables they reference change.
