### ISSUE TITLE
Document that updating the README is part of the release process

### ISSUE THREAD

**Issue by ethan-readyset** [readysettech/readyset#199]
Currently, we tag our beta releases with the date on which they are created. This makes sense, but it means that we need to update the docker command in the quick start section of the README any time we push a new beta release. This should be documented wherever we document our release process to ensure that it is done with every release.

**Comment by ethan-readyset** [comment]
> Alternatively, we should make sure to document that updating the readme is part of our release process.

This.

**Comment by ronh-rs** [comment]
The docker command no longer needs to be updated on each release, as we now use the `current` tag.  Cancelling this ticket.
