### ISSUE TITLE
Cached data are inaccurate after sysbench

### ISSUE THREAD

**Issue by readyset-railway** [readysettech/readyset#206]
### Summary

When a cache is created after a considerable amount of transactional queries, the cached data is inaccurate.

### Description

The inaccuracy happens under these conditions :

1. Number of threads doesn't matter. 
2. Number of tables should be at least 2.
3. Queries should be transactional and each transaction should UPDATE more than one table.
4. Cache should be created after running sysbench. Even if the cache exists, running the "CREATE CACHE" query again would replicate this issue.
5. When the cache exists, running something like "UPDATE sbtest1 SET k=id" and then running the tests again without recreating caches would also replicate this bug.
6. Whenever the data inaccuracy occurs, restarting RS and comparing cache data always give the correct results. (You can use "--only-compare" option in the scripts).

Extra information : [https://readyset-workspace.slack.com/archives/C01HF1WTP6Y/p1689701470725189](https://readyset-workspace.slack.com/archives/C01HF1WTP6Y/p1689701470725189)

### Steps to reproduce 

The scripts in "hacks/sandaru1/general-system-testing/restart/" would be able to replicate the issue.

1. Change the parameters in params.sh to connect to your upstream DB and the RS instance.
2. Start with a blank database and a new RS deployment.
3. Run the following command : 

   ```
   ./accuracy-check.sh  --recreate-caches --threads=1 --tables=2 --init-db
   ```
   1. "--init-db" can be dropped after the first run
   2. "--recreate-caches" forces the query "CREATE CACHE FROM SELECT…" even if the cache exists.
   3. Use "--only-compare" to ignore sysbench and compare the cache vs upstream.
   4. "--show-diff-output" would show the differences between RS cache and the upstream.
4. Once the invalid caches are shown, restarting RS and running the script again (without --recreate-caches and --init-db) would give the correct results.

### ReadySet version

641f8796fbc2d23ab058eaecca3f1c98b317ffab

### Upstream DB type and version

PostgreSQL 15.3

**Comment by readyset-railway** [comment]
Might be related [REA-3118](https://linear.app/readyset/issue/REA-3118/investigate-skipping-table-action-for-earlier-entry-log-lines)

**Comment by ethan-readyset** [comment]
Confirmed to be fixed by REA-3118
