### ISSUE TITLE
Connectivity testing

### ISSUE THREAD

**Issue by gvsg-rs** [readysettech/readyset#207]
We want to make sure that ReadySet recovers in the presence of random network faults. To test this, we should use the AWS test bed built out in [REA-3019](https://linear.app/readyset/issue/REA-3019/create-mock-production-environment) as a base and then add a way to inject and remove connection faults to test recovery behavior. We could inject network failures by either modifying the routing tables, or with some library or framework like [https://github.com/tokio-rs/turmoil](https://github.com/tokio-rs/turmoil/).

There are a few possible scenarios we hope to test here:

* A network fault disrupts the connection between a client and ReadySet. In this case, there's not much we can do — it will be up to the client to handle the disconnection gracefully. We do want to make sure that ReadySet doesn't crash or leak any resources here.
* A network fault disrupts the connection between ReadySet and the upstream database during a proxied query. We should make sure that we 1) don't crash and 2) log/return an appropriate error.
* A network fault disrupts the connection between a client and ReadySet during a `CREATE CACHE` statement.
* A network fault disrupts the connection between ReadySet and the upstream database during replication. Here, we should make sure that we enter a retry loop to re-establish a connection. When the connection is re-established, we should make sure we catch up starting from the last replication offset we successfully applied to a table.

This test will be done in standalone mode — testing ReadySet with an HA configuration is out-of-scope for this ticket. We should reuse the test bed we've developed for the long-running system test, using sysbench to generate consistent load against ReadySet and then randomly inject a fault in the network to prevent ReadySet's EC2 instance from reaching the upstream database.

**Comment by ethan-readyset** [comment]
We used [toxiproxy](https://github.com/Shopify/toxiproxy#clients) to perform some randomized connectivity testing as part of the work in this issue and found no bugs. We will perform further testing as part of Jepsen testing in [Warm-Read HA](https://linear.app/readyset/project/warm-read-ha-064b622d9d86/REA)
