### ISSUE TITLE
Ensure backwards-incompatible updates to controller state don't unnecessarily resnapshot

### ISSUE THREAD

**Issue by glittershark** [readysettech/readyset#216]
If we make a backwards-incompatible change to the serialization of the controller state, we shouldn't have to resnapshot the actual data in the base tables (assuming the schema hasn't changed since we stopped running) - we should make sure this happens

**Comment by lukoktonos** [comment]
[https://gerrit.readyset.name/c/readyset/+/6375/1](https://gerrit.readyset.name/c/readyset/+/6375/1) includes the change above
