### ISSUE TITLE
Wrong column type returned from numeric Rails query in postgres

### ISSUE THREAD

**Issue by glittershark** [readysettech/readyset#223]
see [https://discord.com/channels/996659489702944828/1065313940868956240/1065353008491282603](https://discord.com/channels/996659489702944828/1065313940868956240/1065353008491282603)

The following query:

`SELECT  1 AS one FROM "blocked_users" WHERE "blocked_users"."author_id" = $1 AND "blocked_users"."user_id" = $2 LIMIT $3`

breaks ActiveRecord 5.2.6 with the following error message:

```
  ↳ app/controllers/api/v1/users_controller.rb:12
  User Load (3.1ms)  SELECT  "users".* FROM "users" WHERE "users"."deleted_at" IS NULL AND "users"."id" = $1 LIMIT $2  <["id", 1>, <"LIMIT", 1>]
  ↳ app/controllers/application_controller.rb:23
  BlockedUser Exists (1.1ms)  SELECT  1 AS one FROM "blocked_users" WHERE "blocked_users"."author_id" = $1 AND "blocked_users"."user_id" = $2 LIMIT $3  <["author_id", 2>, <"user_id", 1>, <"LIMIT", 1>]
  ↳ app/controllers/api/v1/users_controller.rb:14
Completed 500 Internal Server Error in 282ms (ActiveRecord: 151.2ms)



ActiveRecord::StatementInvalid (PG::IoError: ERROR:  decode error: invalid type: 0
: SELECT  1 AS one FROM "blocked_users" WHERE "blocked_users"."author_id" = $1 AND "blocked_users"."user_id" = $2 LIMIT $3):```
```

**Comment by glittershark** [comment]
I know we fixed something like this recently, I’d be interested in if it still repros.

**Comment by aglover** [comment]
User reported most recent version of ReadySet addressed this issue. Thank you Nino!!
