### ISSUE TITLE
Re-run stored CREATE CACHE statements after snapshotting if we dropped controller state

### ISSUE THREAD

**Issue by glittershark** [readysettech/readyset#233]
Once `CREATE CACHE` statements are being stored as strings in the authority, we can re-run them one by one if we've dropped the controller state due to making a backwards-incompatible change in serialization

**Comment by lukoktonos** [comment]
[https://gerrit.readyset.name/c/readyset/+/6326](https://gerrit.readyset.name/c/readyset/+/6326)
