### ISSUE TITLE
Memory Stress Test

### ISSUE THREAD

**Issue by lukoktonos** [readysettech/readyset#241]
Make one or more memory stress tests that perform inputs that will result in the unbounded state/queues [in this doc ](https://docs.google.com/document/d/1tQTwCfKcaSsKB2QSHqtRCPyO5pQp9caS-LXMV2qtIf8/edit)becoming a problem, and the bounded ones filling up.

**Comment by lukoktonos** [comment]
[https://gerrit.readyset.name/c/readyset/+/5805](https://gerrit.readyset.name/c/readyset/+/5805) adds a way to run readyset in HA configuration with optional memory limits for use in testing

**Comment by lukoktonos** [comment]
## **How does the system behave if we don't have enough memory to finish snapshotting?**

* If we have a db size 170MB and snapshot, docker uses \~330MB of memory, then drops to 211MB steady state.
* If we don’t have enough memory to snapshot, the server is oomkilled and restarts
* 280MB was enough to finish, so rocksdb must dial back its memory usage somewhat in memory-restricted environments, but there is a lower bound at which we can get in an oom loop.
* Once we finish snapshotting, even 90MiB is enough to come back up.
* Provisioning the container with more memory and restarting gets us out of the oom loop.
* How would we detect this snapshot failure loop?
  * Snapshot status stays in “In Progress” forever in the case of an oom loop.
  * We probably want some # of tables snapshotted or something here that we can timeout eventually?
  * Something like a sustained server start/restart metric going off would probably be the clue, then we could find it from the logs.

## **How does the system behave if there are a ton of unique proxied queries, which make the QueryStatusCache/QueryLogger grow?**

* Running queries that are proxied consumes memory that is roughly the size of the query string. We do rewrite some queries to coalesce parameters, but there are some that are not rewritten and reported as unique queries
* Running enough of these makes the adapter OOM
* On restart, the adapter does not remember the previously run queries, so the system recovers memory-wise on restart. This applies both to the QueryStatusCache, which holds the query string, and the QuerryLogger, which holds a histogram per query.
* Since queries are generally pretty small, meaning it would take quite a long time to grow large enough to be problematic, and the system recovers after a restart (and we are likely to restart for other reasons like deployments, etc. before this grows large enough), this has fairly low impact.
* Note: This behavior may change if we implement [REA-3081](https://linear.app/readyset/issue/REA-3081/persist-show-proxied-queries)

  ## Other Notes
  * While it was possible to observe the behavior of the system, it involved ignoring a *lot* of noisy error/warning logs that users will not necessarily know are OK.
    * Particularly on adapter/server restarts, there is some time before the system recovers where there are lots of warn and error logs spammed in the logs. If there is a restart loop caused by OOMing, these are pretty much constant
  * For the unbounded queues and other things mentioned in the doc, I don't think there will be a high enough ROI to extend these tests for those at this point--it will probably be more useful to move on to eviction testing.

**Comment by gvsg-rs** [comment]
> * Running queries that are proxied consumes memory that is roughly the size of the query string. We do rewrite some queries to coalesce parameters, but there are some that are not rewritten and reported as unique queries

Do we then think [REA-3081](https://linear.app/readyset/issue/REA-3081/persist-show-proxied-queries) and [REA-3210](https://linear.app/readyset/issue/REA-3210/fix-querylogger-unbounded-memory-usage) are higher priorities than what we have assigned them so far? Will running ReadySet for a few days with a lot of queries inevitably cause us to crash?

**Comment by lukoktonos** [comment]
To clarify, the memory consume is per unique proxied query, so repeated queries that are the "same" will not consume additional memory. We do some rewriting of literals to coalesce these queries already. So it would take either quite a lot of unique queries or some particularly unrealistic queries that are very, very large in order to make a real memory impact.

For a data point, a gitlab deployment (at least a little bit after startup) has around 2000 proxied quries which end up taking probably at most a few mb worth of memory.

\>Do we then think [REA-3081](https://linear.app/readyset/issue/REA-3081/persist-show-proxied-queries) and [REA-3210](https://linear.app/readyset/issue/REA-3210/fix-querylogger-unbounded-memory-usage) are higher priorities than what we have assigned them so far? 

It doesn't look like [REA-3081](https://linear.app/readyset/issue/REA-3081/persist-show-proxied-queries) has been prioritized yet, so I'm not sure about that one.

[REA-3210](https://linear.app/readyset/issue/REA-3210/fix-querylogger-unbounded-memory-usage) shouldn't really be a blocker for Day0/1/2 experience either currently, although both of those issues do have interesting interactions with [https://linear.app/readyset/issue/](https://linear.app/readyset/issue/REA-3389)[REA-3389](https://linear.app/readyset/issue/REA-3389/enable-metrics-in-show-proxiedcaches-command).
