### ISSUE TITLE
Expose adapter metrics via status commands

### ISSUE THREAD

**Issue by dfwilbanks395** [readysettech/readyset#260]
**Description**

Allow querying certain adapter metrics and connectivity errors

* Last startup
* Parse errors
* ReadySet query result errors
* ViewNotFound errors and replaced views
* Other RPC errors
* Disallowed set statements received

Investigate other adapter metrics that would be useful to query via a status command

**Change in user-visible behavior**

Users will be able to query adapter status information via status commands

**Requires documentation change**

Yes

**Comment by jasobrown-rs** [comment]
@aglover / @gvsg-rs We currently have `show readyset status`, whose intent is supposed to be more centered around snapshot/replication status \[[docs](https://docs.readyset.io/cache/check-snapshotting#check-overall-status)\]. The data points to be dumped as this ticket are not related to snapshotting, thus I think we'll need a new status command. Should we introduce a new SQL command, like `show readyset adapter status` or something similar?

/cc @glittershark as I'm not sure if we have any posture or philosophy about adding new SQL commands. Any context you can share would be great!

**Comment by jasobrown-rs** [comment]
fwiw, we also have `show readyset migration status <id>` as another "status" command.

**Comment by aglover** [comment]
`SHOW READYSET STATUS` appears as a table - would it be possible to add new rows to it that outline some of those other aspects like 

Last Startup time | <some time>

Parse Errors | Something like "true" and direct them to view to logs?

**Comment by gvsg-rs** [comment]
Hi Jason - what other SQL extensions do we currently have? Its not currently documented in our docs pages unfortunately.

**Comment by jasobrown-rs** [comment]
Yes, it's reasonably easy to add those new metrics, as called for in this ticket, to the existing `show readyset status`. However, my understanding is that `show readyset status` is for snapshot/replication stuffs. If we want to go ahead and make `show readyset status` a general 'grab bag' of properties, that's fine although it might become unwieldy over time if we keep adding things. Hence, I'm wondering if it's better from a product PoV to introduce further commands, or if we should keep it simple.

**Comment by jasobrown-rs** [comment]
@gvsg-rs Yeah, I'm not sure how much is 'public', just reading the code :) At a minimum, we have

* `show caches`
* `show proxied queries`
* `show readyset version`
* `show readyset status`
* `show readyset tables`
* `show readyset migration status <id>` 

I *think* there's also `show events` and `show tables` , at least in the code, but they don't work for me (against PG). Not sure what those are tbqh.

**Comment by gvsg-rs** [comment]
I'd like to hear from @Aspen if we have a documented philosophy.

But I agree with your instinct that we should carefully consider the extension commands that we put out so that they don't change frequently in future and cause distress to our paying customers.

Thoughts, @Andy

**Comment by jasobrown-rs** [comment]
Another thing we could do is add a "category" column or something that groups the properties to together. For example:

**Comment by gvsg-rs** [comment]
I don't think we explain what the Adapter is anywhere in our documentation and we should refrain from exposing this to customers. If the phrase (eg. Adpater → Upstream) can be something user relatable it seems reasonable.

**Comment by gvsg-rs** [comment]
Looks like we do use the phrase "[Adapter](https://docs.readyset.io/concepts/ha#running-readyset-in-ha-mode)" - as part of our recently added HA documentation.

**Comment by jasobrown-rs** [comment]
Yeah, my basic thrust here is "should we categorize these results in some way, or is a (potentially unsorted) laundry list of name/value pairs good enough?"; the labels/commands are an implementation detail.

**Comment by jasobrown-rs** [comment]
[CL](https://gerrit.readyset.name/c/readyset/+/6076/1)

**Comment by jasobrown-rs** [comment]
given the alignment on the [RFC for SQL extentions](https://docs.google.com/document/d/1Cmx8dBy8xbRlMlAxjcwH0syWlXguYs1lR1Z2JizPw3c) (at least, no major disagreements yet), I will pursue creating SQL commands in the form `SHOW READYSET STATUS <cmd>`, including for this ticket.

@aglover Given ^^, I will create `SHOW READYSET STATUS ADAPTER` for this ticket. If we want to use a different noun vs "adapter", it's easy enough to change, but I'll plow ahead with "adapter" for now. Let me know if you have other thoughts. fwiw, these SQL extensions for `SHOW READYSET STATUS` are targeting expert users (i.e. us), so I think having a more arcane/internal name might be acceptable. lmk

**Comment by aglover** [comment]
Ok - I don't have a better alternative for Adapter at this point and I think the larger conversation we should align on (but isn't blocking this work) is how to convey the intricacies of our product w/o confusing folks. If we have a command that uses the noun Adapter (or whatever) we need to then define what that is and why someone should care. I really want people to focus on "ReadySet the cache" not "ReadSet the process that has two components Server and Adapter that work together to provide a cache" — I'll continue to think this over.
