### ISSUE TITLE
ReadySet does not handle unsupported parameters issued as TEXT

### ISSUE THREAD

**Issue by dfwilbanks395** [readysettech/readyset#266]
Reported by @readyset-railway:

In a Postgres deployment, given the query `SELECT * FROM foo WHERE foo.unsupported_type = ?`, ReadySet will fail to proxy if the parameter sent in the BIND message uses the Text format.

Related to [111](https://github.com/readysettech/readyset/issues/111)

**Comment by nickelization** [comment]
Actually, my previous comment was wrong, this is an entirely independent issue from #268, since the encoding formats for parameters are handled by totally different code than encoding formats for result sets.
