### ISSUE TITLE
Table deny list

### ISSUE THREAD

**Issue by dfwilbanks395** [readysettech/readyset#274]
The `--replication-tables` config allows a user to specify the set of tables that they would like replicated, but we do not provide the user with a way to selectively deny replicating a table. This would be especially useful for users that have large tables that they know they won't want to cache from.

**Comment by dfwilbanks395** [comment]
We can do the same thing as we do for bugs – and put it into the ready-for-development / TODO list.

**Comment by dfwilbanks395** [comment]
<\~accountid:6386c6e93c26ca7fa0d52b22> what’s our process for scheduling work that is not a bug?

**Comment by lukoktonos** [comment]
This is completed with --replication-tables-ignore.
