### ISSUE TITLE
Webhooks support to persist data to third party end-points

### ISSUE THREAD

**Issue by pythonpen** [readysettech/readyset#31]
**Is your feature request related to a problem? Please describe.**
See a potential to have a feature to move 3rd party data integrations closer to the DB. For example, based on some condition or CRUD operations on any db table - to be able to post data to 3rd party end-points via https POST

**Describe the solution you'd like**
Maybe add an easy to use configurable user interface to build such Integrations and along with a feature to view all the request / response logs for traceability. 

**Describe alternatives you've considered**

**Additional context**
Since keeping integrations in the application layer can be tricky some cases leading to data inconsistency - it is always fail safe to handle data integrations closer to the DB right before a CRUD operation.

A usecase would be to send data generated in a legacy system to a new system

**Comment by jbensal** [comment]
Thanks @pythonpen ! Have you looked for a solution like this today? Are there any integrations you'd like to use today but can't?

I'll sync with the team and put this on our roadmap, but we're realistically not going to be able to tackle this for a while. Thanks for starting the discussion!

**Comment by pythonpen** [comment]
Thanks @jbensal for consideration in the roadmap - Sure, it can be long short. Just made a suggestion only - for having this as an add-on capability in ReadySet. 

Today this type of realtime ETL requirements are coded at the application level via webhooks (which works pretty good - but not very reliable sometimes due to bugs in the code or application failures), however if such integrations are moved closer to the DB it can be more reliable and can ascertain the ACID properties for the data. 

For high fidelity data inter-operability applications in the domain of Healthcare (Patient Health Record - inter-ops etc), having such reliable solutions will greatly help.

I don't know yet if such realtime ETL capabilities exists native to the DB - maybe PostREST can do it or Store Procedures can do it. 

But see if it makes sense to add this as a feature extension some day in ReadySet.

**Comment by pythonpen** [comment]
This is a nice problem to solve for - even as a separate product I guess
