### ISSUE TITLE
Support for table blacklist instead of whitelist

### ISSUE THREAD

**Issue by PatrickRose** [readysettech/readyset#32]
**Is your feature request related to a problem? Please describe.**
I'm currently trialling ReadySet and I already know there are 2-3 tables that I'd like to not bother ReadySet with at all (because they're read from so infrequently *and* they're massive). Currently, the only option is to write out a whitelist of tables with the `--table-replication` flag, which doesn't work well for us because we have 300+ tables plus we'll be adding new tables all the time.

**Describe the solution you'd like**
A command line flag for the tables that ReadySet shouldn't bother caching, similar to `--table-replication` (`--table-replication-ignore` might work?).

I would guess that `--table-replication` and `--table-replication-ignore` would be mutually exclusive.

**Describe alternatives you've considered**
None, beyond a long whitelist.

**Comment by altmannmarcelo** [comment]
FYI: This is implemented at #400 .
I believe this FR can be closed.
