### ISSUE TITLE
support non clear text password for postgres

### ISSUE THREAD

**Issue by DeoLeung** [readysettech/readyset#33]
**Is your feature request related to a problem? Please describe.**
readyset seems to required clear text password for postgres, see https://github.com/levkk/pgcat/issues/255

**Describe the solution you'd like**
support non clear text authentication

**Comment by greg-mckeon** [comment]
Hey @DeoLeung,

Thanks for the report.  Today, we only support `password` authentication.  If you use an SSL certificate, the password will not be sent in cleartext over the wire.

We're looking into support for the new SCRAM authentication method in Postgres14 - while this is on our roadmap, we don't currently have a timeline for release.

**Comment by glittershark** [comment]
ReadySet now supports `SCRAM-SHA-256` authentication, and uses it by default
