### ISSUE TITLE
When specifying a `--upstream-db-url` without username/password and `--allow-unauthenticated-connections` is false, we don't print a clear error message

### ISSUE THREAD

**Issue by ethan-readyset** [readysettech/readyset#425]
### Summary

When specifying a \`--upstream-db-url\` without username/password and \`--allow-unauthenticated-connections\` is false, we print a confusing error message:

> Error: Must specify --username/-u if one of --allow-unauthenticated-connections or --upstream-db-url is not passed

In my case, `--allow-unauthenticated-connections` was false and I did pass `--upstream-db-url`, but it didn't include a username and password, so we weren't able to use that username/password as ReadySet's.

### Description

The issue at hand here is that we don't propagate up a URL parse error when we fail to parse a username/password from the upstream DB URL here: [https://github.com/readysettech/readyset/blob/c55bad54551ea228e0587aab81a45951c2700309/readyset/src/lib.rs#L469-L483](https://github.com/readysettech/readyset/blob/c55bad54551ea228e0587aab81a45951c2700309/readyset/src/lib.rs#L469-L483)

### Expected behavior

If `--allow-unauthenticated-connections` is false and `--upstream-db-url` is passed without a username/password, I'd expect us to print an error explaining the issue with the upstream DB URL I passed.

### Actual behavior

If `--allow-unauthenticated-connections` is false and `--upstream-db-url` is passed without a username/password, the following error is printed:

> Error: Must specify --username/-u if one of --allow-unauthenticated-connections or --upstream-db-url is not passed

### Steps to reproduce 

Run ReadySet with `--allow-unauthenticated-connections=false` (the default) and an `--upstream-db-url` without a username/password.

### ReadySet version

a5391bcbf

### Upstream DB type and version

N/A

### Instance Details

N/A

### Deployment Details

N/A

### OS Information

N/A

### Logs

N/A

**Comment by amartin96** [comment]
Related ticket: [REA-2917](https://linear.app/readyset/issue/REA-2917/bail-if-upstream-url-is-malformed)

We also want to clean up messages for unrecoverable errors related to the upstream URL, but the error types provided by our postgres and mysql client libraries aren't the most conducive to this.
