### ISSUE TITLE
Reword forbidden-ness associated w/full materialization

### ISSUE THREAD

**Issue by aglover** [readysettech/readyset#458]
`Operation unsupported: Creation of fully materialized query is forbidden` is a bit strong and could be misleading - could we say something like "creation of fully materialized queries are disabled" — and point them to our docs or something for more information?

**Comment by lukoktonos** [comment]
It looks like the docs website page that had the information about the `allow-full-materialization` flag was removed along with a bunch of other hidden cli flags, but I can update the wording to be “disabled”

**Comment by lukoktonos** [comment]
https://github.com/readysettech/readyset/pull/467

**Comment by lukoktonos** [comment]
[https://github.com/readysettech/readyset/pull/467](https://github.com/readysettech/readyset/pull/467)

The docs for `--allow-full-materialization` were removed but this rewords the error to say "disabled".
