### ISSUE TITLE
Local predicates in the ON clause of LEFT JOINs could just be pushed up

### ISSUE THREAD

**Issue by glittershark** [readysettech/readyset#462]
**Description**

I've been seeing a lot of queries that have some sort of equi-join key plus a local predicate comparing a table against a literal issued by Gitlab, eg:

```
SELECT 1 AS "one"
FROM "labels"
LEFT OUTER JOIN "label_priorities" ON (("labels"."id" = "label_priorities"."label_id") AND ("label_priorities"."project_id" = 1))
WHERE (((("labels"."type" = 'GroupLabel') AND "labels"."group_id" IN (2)) OR (("labels"."type" = 'ProjectLabel') AND ("labels"."project_id" = 1))) AND ("label_priorities"."priority" IS NULL))
```

(see that `("label_priorities"."project_id" = 1)` pred)

Currently we don't support non-equi-join-keys in `LEFT JOIN`s because it's tricky to do entirely at the graph level, but for the special case of local predicates (predicates that only mention one table) it would be correct to just push them above the join, which would allow us to support a bunch of these queries

**Change in user-visible behavior**

Support for more queries

**Requires documentation change**

Extension to the query support doc, but this is also kind of hard to explain.

**Comment by ethan-readyset** [comment]
This was done in 7789aae835aa73ef0c339b0f3f6e54daff53aa91
