### ISSUE TITLE
Dogfood Discourse App

### ISSUE THREAD

**Issue by gvsg-rs** [readysettech/readyset#483]
**Description**

Dogfood Discourse as an app against ReadySet. This [doc](https://docs.google.com/document/d/1W1YtQALNGPbR4qQE0w7oZvIlhPKi6vkjeU0svVAaVFQ/edit) has more details.

**Change in user-visible behavior**

No

**Requires documentation change**

No

**Comment by aglover** [comment]
Discourse doc: [https://docs.google.com/document/d/1wLinjA-\_FAeg-vlDRNuFXqKu-qFShzN25nZZOjkgob0/edit?usp=sharing](https://docs.google.com/document/d/1wLinjA-\_FAeg-vlDRNuFXqKu-qFShzN25nZZOjkgob0/edit?usp=sharing)
