### ISSUE TITLE
Running a Scale Test emulating a user's workflow

### ISSUE THREAD

**Issue by gvsg-rs** [readysettech/readyset#484]
**Description**

Run a Scale test emulating a user's workflow as specified in this [doc](https://docs.google.com/document/d/1wLinjA-\_FAeg-vlDRNuFXqKu-qFShzN25nZZOjkgob0/edit#heading=h.sbcdgffj04mr).

**Change in user-visible behavior**

No

**Requires documentation change**

No

**Comment by ethan-readyset** [comment]
Finished with the rest of the discourse testing
