### ISSUE TITLE
Enable periodic RocksDB WAL flushing

### ISSUE THREAD

**Issue by ethan-readyset** [readysettech/readyset#501]
**Description**

Currently, RocksDB is configured to flush the WAL to disk on every write to RocksDB. This has introduced substantial latency in our write path: when a write workload contains a lot of small transactions or a lot of small writes across different tables in the same transaction, we send a lot of small RPCs to the base table domains. Each of these RPCs results in a WAL flush, which introduces a bottleneck into the replication path, since the replicator can only write to one base table domain at a time.

Luckily, we always have the upstream database as a source of truth to use as a recovery mechanism, so we don't have to ensure that the WAL is flushed to disk with every write. That said, we **do** need to make sure we only report our log position to the upstream database using **the maximum replication offset that has been flushed to disk in RocksDB**. If we were to log our position using an unflushed replication offset, the upstream database would think we've persisted everything up to that point already and purge those WAL entries. If this happened and we were to crash, we'd have no way of recovering that data. The right approach here is to enable [manual WAL flushing ](https://docs.rs/rocksdb/latest/rocksdb/struct.Options.html#method.set_manual_wal_flush)and flush the WAL to disk periodically in persistent state.

See [this RFC](https://docs.google.com/document/d/1FxeWArlLOtxQwjhhPPH6B-qX7gHIVXnabg3Q7H7ZYgE/edit#heading=h.a6zf6d33780d) for some discussion as to the right way to implement this.

**Change in user-visible behavior**

No

**Requires documentation change**

No

**Comment by ethan-readyset** [comment]
This will resolve the issue discovered in[REA-3119](https://linear.app/readyset/issue/REA-3119/investigate-replication-lag-occurring-with-rds-aurora)

**Comment by ethan-readyset** [comment]
RFC to evaluate a couple different approaches: https://docs.google.com/document/d/1FxeWArlLOtxQwjhhPPH6B-qX7gHIVXnabg3Q7H7ZYgE/edit#heading=h.a6zf6d33780d

@altmannmarcelo Just wanted to make you aware of this -- since you've been looking at parts of our replication code, I thought you might want to take a look! 😄

**Comment by altmannmarcelo** [comment]
Hi @ethan-readyset . This is great. On some Flamegraphs I sampled for the overflow patch, I could see `rocksdb::DBImpl::WriteToWAL` (especially sync of WAL)  have been responsible for about 25% of CPU time.

I will have a look at the doc tomorrow and check if I have something useful to add. Thanks for the heads up.
