### ISSUE TITLE
Enable ReadySet to read flags from a configuration file

### ISSUE THREAD

**Issue by aglover** [readysettech/readyset#514]
This will be helpful to run a binary easily w/o having to pass in a handful of flags on the command line. It'll enable easier re-running too.

**Comment by gvsg-rs** [comment]
We already have support for environment variables, and that might be the preferred approach to achieving a config file functionality.

**Comment by jasobrown-rs** [comment]
\+1 to the env vars. You can also pass a file with env vars to docker ([docs](https://docs.docker.com/engine/reference/commandline/run/#env)), as well as echoing it for any binary being executed.

fwiw, we could create/ship a default ENV file, and users can modify to their taste (and check into a repo). However, they will be responsible for merging their changes with any future additions/modifications we make to configuration - there's nothing particularly special or novel about that, though.

**Comment by jasobrown-rs** [comment]
@aglover  What's your take on ^^ ?

**Comment by aglover** [comment]
Makes sense, but I'm not sure how this would work in the current single docker file context. I guess we could add a new flag that passes in a file?

**Comment by jasobrown-rs** [comment]
it would be something like:

```
docker run --env-file readyset.env ....
```

iiuc, docker will read that file and expand those into env vars that the process in the container can access as standard env vars. Readyset is programmed to have an env var for every cli flag

**Comment by jasobrown-rs** [comment]
Thus, something like:

**Comment by aglover** [comment]
Yeah, that's clean - and to double check the latter two in the above example will be optional once all DevEx work lands?

**Comment by jasobrown-rs** [comment]
> the latter two in the above example will be optional once all DevEx work lands?

Yup

**Comment by jasobrown-rs** [comment]
OK, @aglover and I agree on the end result (a file with env vars that can be passed to docker or executed in the same session as the binary). There is no code change necessary in readyset itself to achieve this (hooray). I feel like this largely becomes a documentation exercise, and hosted somewhere near here: [https://docs.readyset.io/reference/cli/readyset](https://docs.readyset.io/reference/cli/readyset)

It's unclear if we need to put anything into the readyset repo, per se, like a sample env vars file, of if that should just be something a user could copy/paste from the docs site.

**Comment by aglover** [comment]
I see - so this is really a doc's ticket - @ronh-rs when we have binary packages, how will .env files work?

**Comment by ronh-rs** [comment]
That kind of depends on the use case.  If we optimize for deploying readyset as a service, started with a `systemd` script, then either vars are defined in the `systemd` script or the `readyset` process itself reads a `/etc/readyset/readyset.conf` file or something.

It's probably not a bad idea to actually flesh out some use cases here (unless that's already been done somewhere…)

**Comment by jasobrown-rs** [comment]
holy crap 🤨  [https://docs.mattermost.com/install/install-docker.html#deploy-mattermost-on-docker-for-production-use](https://docs.mattermost.com/install/install-docker.html#deploy-mattermost-on-docker-for-production-use)

**Comment by jasobrown-rs** [comment]
i'm cool with building a sample `env.example` file, but asking a user to clone the `readyset` repo is probably overkill. Hence, my original, naive "can we put it in the docs site" idea (not saying that's great, but perhaps sufficient)

**Comment by ronh-rs** [comment]
Nonono, read that more carefully.  The user isn't cloning the mattermost repo; rather, they're cloning [a docker-deployment repo](https://github.com/mattermost/docker#mattermost-docker-setup) that contains the `compose` files and other configs/scripts necessary to run it with docker (mattermost requires multiple containers).

**Comment by jasobrown-rs** [comment]
yeah, i did see that it was a "scripts and config" repo (rather than a giant repo), but I was more of the "should a user need to clone *anything*?" PoV. Maybe that is the best, though, esp if we'll have more than just a single `readyset.env.example` file.

**Comment by aglover** [comment]
Following variables are required today

1. UPSTREAM_DB_URL
2. LISTEN_ADDRESS
3. PROMETHEUS_METRICS
4. STANDALONE

The latter 3 will become optional in Dec.

**Comment by aglover** [comment]
syntax will be

```
 $> docker run -d -t -i -p 5433:5433 --env-file ./readyset.env readysettech/readyset:latest 
```
