### ISSUE TITLE
Replication lag monitoring

### ISSUE THREAD

**Issue by aglover** [readysettech/readyset#515]
An idea: it'll be helpful to regularly report/alert on replication lag as there are certainly actions operators can take if they're aware of issues. If we assume that we aren't aware of all writes we could take an alternative path where RS has its own table in the upstream db where it periodically writes to it and measures the response time for replication. In this way we could possibly get an understanding of replication lag and then alert/report on it.

**Comment by glittershark** [comment]
I don't think we need to make a table and write to it, we can just ask Postgres to tell us what the current replication lag is on the slot

**Comment by dfwilbanks395** [comment]
Replication lag in ReadySet is the time it takes to write to a base table, plus the time it takes to propagate the write through the dataflow graph to every Reader that needs it.

It's probably best to measure lag per query, with each reader node tracking it's own replication lag. We'd have to make some updates to measure this (probably a timestamp for each set of records), though I don't think it'd be much work.

**Comment by glittershark** [comment]
this is harder than it might seem at first because there can be more than one path from base table(s) to reader node

**Comment by dfwilbanks395** [comment]
I might be over simplifying this, but what's wrong with taking the oldest timestamp of any path? I think multiple paths complicate measuring staleness, but not as much replication lag.

For example, say it takes 10 ms and 100 ms for data to get to the lhs and rhs of a join respectively and then from there it's instantly available at the reader. We insert into both tables, and when we process the records in the join, assume we don't miss looking up into the other side's parent.

When the first insert hits the reader, we'd record a replication lag event of 10 ms, even though the data from the rhs could have been up to 100 ms stale. Likewise, we'd record 100 ms when we get the second insert, even though the data from the lhs was potentially only 10 ms stale.

I'm not completely sure if this was your point, but I don't think it's so bad if these measurements don't capture exactly how stale our data is.

**Comment by gvsg-rs** [comment]
Please continue to talk about this, and provide a triage recommendation.

**Comment by gvsg-rs** [comment]
We discussed this, and decided that this is better measured through pg_stats. Closing this request, and creating a new issue instead.

Get access to pg_stat queries from the customer database so we can use it for internal debugging and figuring out which queries will provide best bang for the buck.

**Comment by gvsg-rs** [comment]
We discussed this, and decided that this is better measured through pg_stats. Closing this request, and creating a new issue instead.
