### ISSUE TITLE
[REA-2374] Memory bloat when running a sysbench workload.

### ISSUE THREAD

**Issue by gvsg-rs** [readysettech/readyset#53]
Setup sysbench on the client.

Download the sysbench-tpcc tests from here:
[https://github.com/Percona-Lab/sysbench-tpcc](https://github.com/Percona-Lab/sysbench-tpcc)

Run the sysbench workload:

```
PHASE=cleanup; PGHOST=db-perf3.c3gkl30tsqmh.us-east-2.rds.amazonaws.com; PGPORT=5432; PGUSER=postgres; PGPASSWORD=ReadySet123; PGDATABASE=postgres; sysbench --db-driver=pgsql --report-interval=2 --tables=10 --scale=20 --threads=8 --time=360 --pgsql-host=$PGHOST --pgsql-port=$PGPORT --pgsql-user=$PGUSER --pgsql-password=$PGPASSWORD --pgsql-db=$PGDATABASE ./tpcc.lua $PHASE
```

ReadySet version is:

```
sh-4.2$ /usr/sbin/readyset --version
readyset
release-version: nightly-2023-03-14
commit_id:       ad3c494e48c20dcc091161042712305f1e6e8f20
platform:        x86_64-unknown-linux-gnu
rustc_version:   rustc 1.64.0-nightly (fe3342816 2022-08-01)
profile:         release
opt_level:       3
```

Backend Database size is reasonable:

```
postgres=> SELECT pg_size_pretty( pg_database_size(‘postgres’) );
 pg_size_pretty
--------------
 3905 MB
(1 row)postgres=> \l
                 List of databases
  Name  | Owner  | Encoding |  Collate  |  Ctype  |  Access privileges
----------<ins>----------</ins>----------<ins>-------------</ins>-------------<ins>----------------------
 postgres | postgres | UTF8   | en_US.UTF-8 | en_US.UTF-8 |
 rdsadmin | rdsadmin | UTF8   | en_US.UTF-8 | en_US.UTF-8 | rdsadmin=CTc/rdsadmin</ins>
      |     |     |       |       | rdstopmgr=Tc/rdsadmin
 template0 | rdsadmin | UTF8   | en_US.UTF-8 | en_US.UTF-8 | =c/rdsadmin     <ins>
      |     |     |       |       | rdsadmin=CTc/rdsadmin
 template1 | postgres | UTF8   | en_US.UTF-8 | en_US.UTF-8 | =c/postgres     </ins>
      |     |     |       |       | postgres=CTc/postgres
(4 rows)
```

Many messages like this are seen in the logs:

```
{“timestamp”:“2023-03-15T14:44:55.022793Z”,“level”:“WARN”,“fields”:{“message”:“Skipping table action for earlier entry”,“context”:“LogContext({\“deployment\“: \“gg-rs-3-14_h9DStCSPCxCG\“})“,”table”:“public.order_line4”,“pos”:“wal<17/97F14808>“,”cur”:“wal<17/97F7B8F0>“},“target”:“replicators::noria_adapter”}
{“timestamp”:“2023-03-15T14:44:55.023207Z”,“level”:“WARN”,“fields”:{“message”:“Skipping table action for earlier entry”,“context”:“LogContext({\“deployment\“: \“gg-rs-3-14_h9DStCSPCxCG\“})“,”table”:“public.order_line4”,“pos”:“wal<17/97F27198>“,”cur”:“wal<17/97F7B8F0>“},“target”:“replicators::noria_adapter”}
{“timestamp”:“2023-03-15T14:44:55.023597Z”,“level”:“WARN”,“fields”:{“message”:“Skipping table action for earlier entry”,“context”:“LogContext({\“deployment\“: \“gg-rs-3-14_h9DStCSPCxCG\“})“,”table”:“public.order_line4”,“pos”:“wal<17/97F3ACB8>“,”cur”:“wal<17/97F7B8F0>“},“target”:“replicators::noria_adapter”}
{“timestamp”:“2023-03-15T14:44:55.023989Z”,“level”:“WARN”,“fields”:{“message”:“Skipping table action for earlier entry”,“context”:“LogContext({\“deployment\“: \“gg-rs-3-14_h9DStCSPCxCG\“})“,”table”:“public.order_line4”,“pos”:“wal<17/97F4CA90>“,”cur”:“wal<17/97F7B8F0>“},“target”:“replicators::noria_adapter”}
```

ReadySet command line arguments:

```
sh-4.2$ ps -ef | grep readyset
root     13928     1 75 13:23 ?        00:55:00 /usr/sbin/readyset --database-type postgresql --deployment=gg-rs-3-14_h9DStCSPCxCG --upstream-db-url=<ins>postgres://postgres:ReadySet123@db-perf3.c3gkl30tsqmh.us-east-2.rds.amazonaws.com:5432/postgres</ins> --username=postgres --password=ReadySet123 --address=0.0.0.0:5433 --log-format=json --prometheus-metrics --query-log --standalone
```

Observation:
Resident memory size for ReadySet increased from 4GB to 76GB after which it was killed by the OOM killer.

```
<67965.936652> Out of memory: Kill process 6376 (readyset) score 958 or sacrifice child
<67965.942972> Killed process 6376 (readyset) total-vm:76136904kB, anon-rss:63694048kB, file-rss:0kB, shmem-rss:0kB
<67967.470299> oom_reaper: reaped process 6376 (readyset), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

Get in touch with <\~accountid:6386c6e93c26ca7fa0d52b22> for a repro. I will upload logs soon.

<sub>From [SyncLinear.com](https://synclinear.com) | [REA-2374](https://linear.app/readyset/issue/REA-2374/memory-bloat-when-running-a-sysbench-workload)</sub>

**Comment by gvsg-rs** [comment]
I wonder if this is related to the fact that writes are being directed through ReadySet, rather than exclusively against the upstream

**Comment by gvsg-rs** [comment]
All queries were proxied.

**Comment by gvsg-rs** [comment]
<\~accountid:6386c6e93c26ca7fa0d52b22> were you caching queries here? or was this just when running proxied queries?

**Comment by lukoktonos** [comment]
I was unable to reproduce an OOM event with the provided instructions.

I ran the provided sysbench workload against a docker postgres upstream in 4 configurations:

1. Against the upstream directly
2. Against readyset with no caches enabled (proxying everything)
3. Against readyset with all (1672) supported caches created (cold caches)
4. Against readyset again with the caches theoretically warmed up (warm caches)

Throughout the runs, memory usage stayed stable and was fairly minimal (only
got up to 5% memory usage on my 32GB memory macbook). This makes sense given that the upstream db size is only around 3 GiB, and not all queries/rows make their way into readyset caches.

See attachments for sysbench performance results (which aren't great but that is probably due to proxying most things) as well as memory usage throughout the runs, which was stable.

[sysbench_results](https://uploads.linear.app/76d4be3b-10f5-452e-a0bd-5ce299bfcdf4/4e5fad29-0194-4684-b4c6-9db0536a4008/7d487c5f-7a07-4b4a-91bf-c4f7cb05c3a1)

[memory_usage](https://uploads.linear.app/76d4be3b-10f5-452e-a0bd-5ce299bfcdf4/b1e74b7d-e727-4e6f-abd2-bb2efb283d7e/198a8956-1266-481a-8bb5-165a8b4a014a)

**Comment by gvsg-rs** [comment]
Thanks, Luke. I'll see if I'm able to recreate it. Its possible that we have also fixed the issue recently.
