### ISSUE TITLE
Parse MySQL Bit-Value literals

### ISSUE THREAD

**Issue by cameronbraid** [readysettech/readyset#54]
See: https://dev.mysql.com/doc/refman/8.0/en/bit-value-literals.html

**Describe the problem**

The following create table statement fails to be parsed

```
CREATE TABLE `table` (
            `enabled` bit(1) NOT NULL DEFAULT b'0',
            `lastModified` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
)
```

There are two causes
* for the enable column it doesn't like `b'0'` (this issue)
* for the lastModified column it doesn't like the `current_timestamp` argument `6` (#56)

The statement was generated for a table in percona xtradb 8.0.27-18.1

**Comment by glittershark** [comment]
Thanks for the great report @cameronbraid! I'm going to split this into two issues (the binary literal issue and the current_timestamp precision issue). I'll repurpose this one for the former.
