### ISSUE TITLE
The SQL column type 'INTERVAL' causes an internal error when parsed.

### ISSUE THREAD

**Issue by tbjuhasz** [readysettech/readyset#572]
**Description**

The SQL column type 'INTERVAL' causes the int_type function in nom_sql/src/sql_types.rs to fail. If a table is created with an 'INTERVAL' column type, it produces the following internal error:

Internal error in 'replicators/src/postgres_connector/snapshot.rs:453:50': Could not parse SQL type. Failed to parse query - expected end of input but got 'erval'.

Steps to reproduce the issue.

Create a table with an INTERVAL column.

```
CREATE TABLE Task (
    id SERIAL PRIMARY KEY,
    task_name VARCHAR(255),
    start_time TIMESTAMP,
    duration INTERVAL
);
```

Once the table is created and ReadySet attempts to parse the 'INTERVAL' type, it produces the following error:

Internal error: in replicators/src/postgres_connector/snapshot.rs:453:50: Could not parse SQL type: failed to parse query, expected end of input but got: 'erval'

**Change in user-visible behavior**

**Requires documentation change**

**Comment by glittershark** [comment]
this is not a bug, we just don't support that type

**Comment by tbjuhasz** [comment]
Other unsupported types are handled differently. We should handled all unsupported types the same way. Usually they are reported as the following:

Operation unsupported: in readyset-data/src/type.rs:310:32: Unsupported type: xml

However, in the case of the 'INTERVAL' type, it produces an internal error.

**Comment by glittershark** [comment]
it's untenable to try to perfectly parse everything in SQL, so we have to be able to handle both things we can't parse and things we can parse but don't support.

Unless there's user-facing impact of this besides the error message?

**Comment by tbjuhasz** [comment]
It is a bad user experience to produce an internal error for for unsupported types. It will cause someone to spend quite bits of time trying to figure out why there is an internal error in the logs.
