### ISSUE TITLE
Add Support for MySQL Binary Log Transaction Compression

### ISSUE THREAD

**Issue by altmannmarcelo** [readysettech/readyset#634]
**Is your feature request related to a problem? Please describe.**
MySQL has added support for ZSTD binary log compression in version 8.0.20. This is widely used on production deployments to reduce bandwidth to ship binary logs as well as to reduce the space they occupy on disk. 
Currently, ReadySet throws an error if it encounters a binlog event of type TRANSACTION_PAYLOAD.

**Describe the solution you'd like**
Once https://github.com/blackbeam/rust_mysql_common/pull/104 is accepted and merged by upstream, proper support can be added to ReadySet.

On RS side, once an event of this type is parsed, the uncompressed payload has to be interpreted as a set of new binary log events.

There is one tricky part with regard to position. All inner events (decompressed events) will all have the same position. They might have to be grouped as a single vector of change list and propagated to Noria at once.

**Describe alternatives you've considered**
The only alternative is to set `binlog_transaction_compression` to OFF.

**Additional context**

MySQL WL - https://dev.mysql.com/worklog/task/?id=3549

**Comment by altmannmarcelo** [comment]
In short, a Transaction_Payload event is a group of events in the same transaction compressed as a single event in the binary log.
The receiver side has to uncompress the event and interpret the uncompressed payload as a set of multi-individual events.
It has the nuance of all inner events having the same position stamp (the end_position of the parent Transaction_Payload event):

Query:

```
START TRANSACTION;
INSERT INTO tb1 VALUES (1);
INSERT INTO tb1 VALUES (2);
COMMIT;
```

This will result in the following:

```
# at 16302
#230927 22:23:04 server id 1  end_log_pos 16469 CRC32 0xf2a25a3d 	Transaction_Payload		payload_size=132	compression_type=ZSTD	uncompressed_size=260
```

Decompressing the Payload:

```
# Start of compressed events.
# at 16469
#230927 22:22:58 server id 1  end_log_pos 16469 CRC32 0xb4a19301 	Query	thread_id=84	exec_time=0	error_code=0
SET TIMESTAMP=1695864178/*!*/;
BEGIN
/*!*/;
# at 16469
#230927 22:22:58 server id 1  end_log_pos 16469 CRC32 0xcb6743f9 	Table_map: `test`.`tb1` mapped to number 135
# has_generated_invisible_primary_key=0
# at 16469
#230927 22:22:58 server id 1  end_log_pos 16469 CRC32 0x051d289e 	Write_rows: table id 135 flags: STMT_END_F

BINLOG '
ctUUZRMBAAAAMQAAAAAAAAAAAIcAAAAAAAEABHRlc3QAA3RiMQABAwABAQEA+UNnyw==
ctUUZR4BAAAAKAAAAAAAAAAAAIcAAAAAAAEAAgAB/wABAAAAnigdBQ==
'/*!*/;
# at 16469
#230927 22:23:00 server id 1  end_log_pos 16469 CRC32 0xb4f1bed3 	Table_map: `test`.`tb1` mapped to number 135
# has_generated_invisible_primary_key=0
# at 16469
#230927 22:23:00 server id 1  end_log_pos 16469 CRC32 0xde68708c 	Write_rows: table id 135 flags: STMT_END_F

BINLOG '
dNUUZRMBAAAAMQAAAAAAAAAAAIcAAAAAAAEABHRlc3QAA3RiMQABAwABAQEA077xtA==
dNUUZR4BAAAAKAAAAAAAAAAAAIcAAAAAAAEAAgAB/wACAAAAjHBo3g==
'/*!*/;
# at 16469
#230927 22:23:04 server id 1  end_log_pos 16469 CRC32 0x826dbd76 	Xid = 1026
COMMIT/*!*/;
# End of compressed events.
```

| Event | Start Pos |  End Pos |  |
| ------------- | ------------- | ------------- | ------------- |
| QUERY_EVENT | 16469  | 16469  | |
| TABLE_MAP_EVENT | 16469  | 16469  | |
| WRITE_ROWS_EVENT | 16469  | 16469  | This results in a ReplicationAction::TableAction |
| WRITE_ROWS_EVENT | 16469  | 16469  | This results in a ReplicationAction::TableAction |
| XID_EVENT | 16469  | 16469  | |

If RS applies the event from the first INSERT query and processes the ReplicationAction::TableAction, it updates the table position; then the second event will be skipped as it will be identified as an early event - https://github.com/readysettech/readyset/blob/beta-2023-08-23/replicators/src/noria_adapter.rs#L898

To overcome this, I can think of the following:

1. Adjust `connector.next_action` & current connectors to return a vector of `ReplicationAction` and make `self.handle_action` process each entry
2. Delegate `handle_action` responsibilities down to each connector so they can implement their own
3. Create a new [ReplicationAction](https://github.com/readysettech/readyset/blob/beta-2023-08-23/replicators/src/noria_adapter.rs#L46) to handle actions from multiple tables at once, something like:
```
pub(crate) enum ReplicationAction {
. . .
    TableActions {
      actions: Vec<(TableAction)>
    },
. . .
```

IMHO, option 3 makes more sense.

@glittershark @ethan-readyset Before I start exploring it, do you have any other suggestions or concerns to consider?

**Comment by altmannmarcelo** [comment]
EDIT: Option 3 actually will not be the best solution here. We also have to consider `DdlChange`.
I think option 1 will be the best long-term option. Changes to pg connector are minimal.

**Comment by jasobrown-rs** [comment]
Merged
