### ISSUE TITLE
Support non-default Kubernetes namespaces

### ISSUE THREAD

**Issue by alanamarzoev** [readysettech/readyset#64]
<sub>From [SyncLinear.com](https://synclinear.com) | [REA-2749](https://linear.app/readyset/issue/REA-2749/support-non-default-kubernetes-namespaces)</sub>

**Comment by amontalban** [comment]
It should be possible already to set the namespace to deploy the chart in a different namespace by supplying the `-n` parameter to Helm, for example:

```
helm install -n readyset readyset . --set readyset.deployment=readyset-helm-chart --create-namespace
```

The above command should be run in `helm/readyset` directory, this will create deploy on the `readyset` namespace and it will create it if not present.
