### ISSUE TITLE
Prevent buildup of RocksDB WAL

### ISSUE THREAD

**Issue by ethan-readyset** [readysettech/readyset#675]
**Description**

If we have many base tables and each table has multiple column families, we end up with many RocksDB memtables. If the write throughput is not particularly high on any of those tables, the memtables could continue to grow without ever being flushed to disk, since they never reach the size threshold at which a flush would occur. This means that the RocksDB WAL files for each of the base tables would *also* grow, since RocksDB needs to keep WAL entries around for any data that hasn't been flushed to an SST file. As long as these writes are persisted in WAL files and not SST files, they can't be compacted, which means we are subject to space amplification, since an update to a value in an LSM tree is really just the updated version of the pre-existing value appended to the end of the file.

To remediate this, we need to trigger memtable flushes in situations where write throughput is low in order to reduce the impact of space amplification and make more efficient use of our disk. There are two primary options:

1. Set [max_total_wal_size](https://docs.rs/rocksdb/latest/rocksdb/struct.Options.html#method.set_max_total_wal_size) to have RocksDB automatically flush memtables to disk when the WAL file exceeds a certain size
2. Manually initiate a memtable flush if one has not occurred over a certain period of time

It's not immediately clear to me which of these two approaches is superior. We don't want to set the max_total_wal_size so low that we trigger very frequent memtable flushes, since that could impact compaction and read performance. On the other hand, it is simpler than periodically flushing memtables ourselves.

**Change in user-visible behavior**

No

**Requires documentation change**

No

**Comment by gvsg-rs** [comment]
My vote is for the "automatic" approach here. max_total_wal_szie should be a percentage of the underlying disk or something like that ideally.

**Comment by ethan-readyset** [comment]
That approach is definitely enticing because it'd be super easy, but it doesn't take into account the total number of base tables in ReadySet (or really, the total number of column families in ReadySet, since each column family gets its own memtable). Each base table has its own RocksDB instance and thus its own RocksDB WAL, so max_total_wal_size would be applied per base table. For example, if we had only had one base table, we could tolerate WAL growth up to 100MB no problem, but if we have 200 base tables, setting max_total_wal_size to 100MB could be problematic

**Comment by jasobrown-rs** [comment]
fwiw, Cassandra has (had?) a configuration to always flush the memtable for a given table after `n` seconds, if it hadn't already been flushed? iirc, it was like 30 minutes or so, but that was for something that had super low write volume. Yeah, the commit log (cassandra's WAL) would grow, but because the the write volume was low, it wasn't a problem in practice.

**Comment by gvsg-rs** [comment]
Ah - I did not realize that max_total_wal_size is applicable per base_table.  

I think flushes need to be space dependent and not time dependent - in our case. Since we must also work with a small installation on a customer demo system. If we are overactive in our flushing, then we won't get compaction benefits. And it is likely that our system also experiences low write volumes.

Here is one possible algorithm:

1\. calculate aggregate wal space across all base tables; (Is there a way to query RocksDB?)

2\. if aggregate wal space used > MAX_AGGREGATE_WAL_HIGH_WATERMARK

3\. get a list of all base tables sorted in descending order by WAL size.

4\. flush the WALs for base tables to disk until wal_space_used < MAX_AGGREGATE_WAL_LOW_WATERMARK.

HIGH_WATERMARK and LOW_WATERMARK should be hysteresis resilient, so that we are not constantly flushing under normal circumstances.

**Comment by VladRodionov** [comment]
I would enable WAL compression as well. We have memory monitor in RS which controls data eviction. I think we should add RocksDB memtable flushing to it as well. Keeping RocksDB memory usage under control is important.

**Comment by VladRodionov** [comment]
Set to delete archived WAL files aggressively and control overall WAL space usage.

**Comment by ethan-readyset** [comment]
Long term, I think base tables that all live on the same worker should share a RocksDB instance (which is something we've discussed before) — that would allow us to set max_total_wal_size. In the immediate term, I'm not sure that there's a quick and easy solution we'll be able to implement — this kind of problem feels RFC-worthy to me, and querying the WAL sizes across all the base tables and coordinating flushes would be a decent-sized code change. I also don't see a way to query for the size of the WAL file for a given db instance.

I looked into WAL compression, and it seems like it's currently a WIP feature: [https://github.com/facebook/rocksdb/blob/1c871a4d8682ea260ba3b18ed43cd525a2141733/include/rocksdb/options.h#L1259C36-L1259C36](https://github.com/facebook/rocksdb/blob/1c871a4d8682ea260ba3b18ed43cd525a2141733/include/rocksdb/options.h#L1259C36-L1259C36)

**Comment by ethan-readyset** [comment]
Perhaps a stop-gap measure here in the short term would be to flush all of the memtables periodically just in case they haven't been flushed. It might create small SST files, but if we just do it once every `n` hours, the impacts of that could/should be pretty small?

**Comment by jasobrown-rs** [comment]
In practice, I suspect this won't be a big problem

**Comment by gvsg-rs** [comment]
Oh - have we seen this happen on the real system? Or is this a theoretical problem? If its theoretical, lets skip fixing it for now.

**Comment by ethan-readyset** [comment]
The problem described in the top-level issue happened in the sysbench long-running test

**Comment by ethan-readyset** [comment]
@jasobrown-rs Were you saying that flushing every `n` hours wouldn't be a big problem or that the problem of growing WAL files wouldn't be a big problem?

**Comment by gvsg-rs** [comment]
If we assume a max of say 200 tables, and we limit WAL size to be 20MB - that gives us about 4GB of disk space. That seems quite reasonable, and we can ask customers to allocate at least 10GB of disk space. 

Thoughts?

**Comment by ethan-readyset** [comment]
I think limiting the WAL size to 20 MB will trigger too many premature memtable flushes. The default memtable size is 64MB (which is what we currently have it set to), so we'd always flush the memtable before it reached its max size. Also, each base table has multiple memtables — one per column family, which means one per primary/secondary key into the base table

**Comment by gvsg-rs** [comment]
In that case, a release note or documentation is a better fix: "If you have a lot of tables, make sure that you allocate a reasonable amount of disk space - at the ratio of 100MB per table."

**Comment by gvsg-rs** [comment]
100MB - to account for multiple memtables per table.

**Comment by ethan-readyset** [comment]
I suspect 100MB wouldn't be enough in some cases 😬 In the sysbench test, there are 4 memtables per base table, which means 64MB\*4=256MB of memtables. The number of memtables is also variable on the number of indexes we create on the base table.

Maybe that's okay for now though?

**Comment by gvsg-rs** [comment]
Sounds good to me.

**Comment by ethan-readyset** [comment]
Okay, action items here are:
\+ Add release note or documentation to note the limitation imposed by RocksDB WAL growth
\+ Open a ticket to investigate having persistent states on a the same worker all share the same RocksDB database

**Comment by ethan-readyset** [comment]
Would be fixed by [REA-3624](https://linear.app/readyset/issue/REA-3624/have-every-base-table-on-a-worker-share-the-same-rocksdb-instance)

**Comment by gvsg-rs** [comment]
Stop gap fix is to document this behavior and mitigate it in the field, when it happens. Longer term fix has been captured in a new ticket.
