### ISSUE TITLE
Fix "Database Connection" status in "SHOW READYSET STATUS" when the connection has yet to connect to upstream.

### ISSUE THREAD

**Issue by jasobrown-rs** [readysettech/readyset#676]
**Description**

`SHOW READYSET STATUS` is displays the status of the current connection, inside the adapter, as it connects to the upstream database.

In the past, the adapter always created a connection to the upstream whenever a client connected to the adapter. In [REA-3432](https://linear.app/readyset/issue/REA-3432/adapter-immediately-opens-upstream-connection-on-simple-tcp-accept), we introduced the `LazyUpstream`, which … lazily connects to the upstream (only when we're actually sending a query to it). Thus, we inadvertently broke `SHOW READYSET STATUS`with this change. Now, before that connection has a chance to send a query to the upstream, we display:

```
Database Connection: Unreachable
```

which sounds scary. However, even a naive `select 1` sends the query the the upstream, and then the status changes to

```
Database Connection: Connected
```

We should at least change the default behavior to not display "unreachable", at least until it's reasonable to do so.

**Change in user-visible behavior**

Yes, but correcting a behavior.

**Requires documentation change**

No.

**Comment by jasobrown-rs** [comment]
The immediate options I can think of:

**Comment by gvsg-rs** [comment]
I like option #1. I like the intentionality of us connecting to the upstream database due to either:
\- Us receiving a query from the client.
\- The customer checking if the upstream connection is okay.

**Comment by jasobrown-rs** [comment]
[CL](https://gerrit.readyset.name/c/readyset/+/6120)
