### ISSUE TITLE
[REA-2750] Support custom deployment names in the Helm chart

### ISSUE THREAD

**Issue by alanamarzoev** [readysettech/readyset#69]
<sub>From [SyncLinear.com](https://synclinear.com) | [REA-2750](https://linear.app/readyset/issue/REA-2750/support-custom-deployment-names-in-the-helm-chart)</sub>

**Comment by imeyer** [comment]
Shipped in verison `0.8.0`. Pass `--set=readyset.deployment=<name>`to `helm install` or pass that via your values file.
