### ISSUE TITLE
Metrics Wishlist

### ISSUE THREAD

**Issue by ethan-readyset** [readysettech/readyset#693]
**Description**

This is a tracking ticket to list all of the metrics we'd like to start tracking to improve observability. If you have a metric you'd like to add, add a comment below!

**Comment by gvsg-rs** [comment]
Do we have a list of existing metrics somewhere?

**Comment by glittershark** [comment]
[http://docs/rustdoc/readyset_client/metrics/recorded/index.html](http://docs/rustdoc/readyset_client/metrics/recorded/index.html)
[http://docs/rustdoc/readyset_client_metrics/recorded/index.html](http://docs/rustdoc/readyset_client_metrics/recorded/index.html)

**Comment by gvsg-rs** [comment]
RPC queue lengths?

**Comment by ethan-readyset** [comment]
Aren't they queued at the receiving end? For both the controller and the domains

**Comment by glittershark** [comment]
no, as of [https://gerrit.readyset.name/c/readyset/+/4956](https://gerrit.readyset.name/c/readyset/+/4956) all controller requests are handled asynchronously

**Comment by ethan-readyset** [comment]
Ohhh right. Well, maybe instead it would be worth counting the number of tasks waiting for locks on DfState. It seems worth tracking queued requests for domains or maybe just domain request response time, especially since requests happen synchronously. Having that kind of  visibility into domain requests could also help us evaluate different solutions for [REA-2961](https://linear.app/readyset/issue/REA-2961/run-domains-in-a-threadpool)

**Comment by gvsg-rs** [comment]
Create individual tickets for every new metric that we want to add.
