### ISSUE TITLE
[REA-2744] Helm chart should output connection info specific to the underlying database type

### ISSUE THREAD

**Issue by alanamarzoev** [readysettech/readyset#70]
Based on whether MySQL or Postgres is passed to the chart, it should output database-specific instructions around how to connect to the ReadySet instance after deployment.

<sub>From [SyncLinear.com](https://synclinear.com) | [REA-2744](https://linear.app/readyset/issue/REA-2744/helm-chart-should-output-connection-info-specific-to-the-underlying)</sub>

**Comment by lukoktonos** [comment]
Ran into this while playing with using the helm chart for testing memory things--figured I might as well knock this off along the way.

[https://gerrit.readyset.name/c/readyset/+/5533](https://gerrit.readyset.name/c/readyset/+/5533)
