### ISSUE TITLE
Audit metric labels

### ISSUE THREAD

**Issue by ethan-readyset** [readysettech/readyset#710]
**Description**

Some of our metric labels are of very high cardinality. For example, our `readyset_query_log_execution_time` metric uses the rewritten query as a label — for deployments that see a lot of distinct queries, we could end up with hundreds or even thousands of different labels for this metric. High label cardinality tends to be extremely taxing on time series databases (see [this](https://docs.influxdata.com/influxdb/cloud/write-data/best-practices/resolve-high-cardinality/) and [this](https://last9.io/blog/how-to-manage-high-cardinality-metrics-in-prometheus/)), making queries very slow. If we have users who are sinking metrics into such a database, they could run into problems.

We should audit our metrics to remove or rework any labels with high cardinality.

**Change in user-visible behavior**

No

**Requires documentation change**

No

**Comment by lukoktonos** [comment]
Related (to the query_log one mentioned above specifically): [REA-3273](https://linear.app/readyset/issue/REA-3273/limit-querylogger-memory-usage)

That one in particular can be somewhat mitigated right now by not using the QUERY_LOG or QUERY_LOG_AD_HOC.

**Comment by gvsg-rs** [comment]
Create new tickets for specific metrics that we notice has high cardinality, and we fix it one by one.
