### ISSUE TITLE
Provide indication of connected clients

### ISSUE THREAD

**Issue by aglover** [readysettech/readyset#749]
Provide a command/status that enables users to understand if their application is connected successfully to ReadySet. If this is a console command, it should report 2 connections for instance.

**Comment by aglover** [comment]
@jasobrown-rs is it possible to add the count of connections to `show readyset status` ?

**Comment by jasobrown-rs** [comment]
Yes, but let's create a separate ticket for that

**Comment by jasobrown-rs** [comment]
[https://linear.app/readyset/issue/REA-3777/add-the-count-of-connections-to-show-readyset-status](https://linear.app/readyset/issue/REA-3777/add-the-count-of-connections-to-show-readyset-status)
