### ISSUE TITLE
Provide users with a connection string upon successful startup

### ISSUE THREAD

**Issue by aglover** [readysettech/readyset#750]
Once ReadySet has successfully initialized (communicates w/upstream and has snapshotted), it should provide users with a connection string they can use to update their application.

**Comment by aglover** [comment]
Ok, that makes sense - perhaps as a stopgap we could somehow indicate that ReadySet is *ready* to be connected to an application. Is there a way we can provide this status perhaps?

**Comment by jasobrown-rs** [comment]
Should I assume that what you are looking for is a log line when everything is A-OK to start doing all the "readyset things" (that is, *after* startup/snapshotting/all the things)?

**Comment by aglover** [comment]
Yeah - perhaps a log line that makes it intuitively clear to operators that ReadySet is ready to proxy queries and cache. I also think we should consider status in the console - if we have snapshotted but not seen any queries, we should make it clear we're waiting for proxied traffic. This part is tricky to some users - they don't realize that they have to point their application at ReadySet and so if we can make it clear from ReadySet's point of view that this *hasn't happened yet* we could help users get there. Does that make sense?

**Comment by jasobrown-rs** [comment]
Makes sense. Adding a log line and a new entry in `show readyset status` seem reasonable.

**Comment by aglover** [comment]
Ok - after chatting w/you and reviewing other tickets I think if we reorder the `show readyset status` table that makes it clear that ReadySet is connected to the upstream and has successfully snapshotted, we should have enough info to elaborate next steps, etc. I think

**Comment by jasobrown-rs** [comment]
ACK 👍

**Comment by jasobrown-rs** [comment]
CL merged
