### ISSUE TITLE
Support for Microsoft SQL Server (MSSQL)

### ISSUE THREAD

**Issue by AndryHTC** [readysettech/readyset#76]
**Is your feature request related to a problem? Please describe.**
As an organization, we extensively utilize Microsoft SQL Server (MSSQL) alongside Postgres and MySQL. Still, MSSQL is one of the widest-used Enterprise DBs world-wide

**Describe the solution you'd like**
We would like to request the addition of MSSQL support in ReadySet. This will allow us to leverage the powerful caching and performance enhancements of ReadySet with our MSSQL-based applications.

**Describe alternatives you've considered**
We've explored other caching solutions (polyscale.ai), but they either require substantial costs. Hence, adding MSSQL support directly to ReadySet would be our preferred solution.

**Additional context**
With the widespread use of MSSQL in many organizations, we believe the addition of MSSQL support could not only benefit us but also many other users who might be looking to enhance the performance of their MSSQL applications. This could also serve to broaden ReadySet's user base, increasing its reach and effectiveness.

Looking forward to your consideration and response.

Best

**Comment by alanamarzoev** [comment]
Hi @AndryHTC, thank you for the request! This is definitely something that we'll do in the long term, but it likely won't make it onto our roadmap within the next year since we have our hands full with just Postgres and MySQL.
