### ISSUE TITLE
 WARN views_synchronizer Could not get view statuses from leader error=Error during RPC (view_statuses): Internal error: request timeout reached!

### ISSUE THREAD

**Issue by eni9889** [readysettech/readyset#877]
Hi,

I just spun up readyset using docker on ubuntu and am getting the messages from the title.

**Comment by aglover** [comment]
Hi @eni9889  - what command did you use to fire up the docker container?

**Comment by eni9889** [comment]
Copy pasted from the docs. I'm on mobile right now I'll have to find the exact command again. @aglover

**Comment by aglover** [comment]
I'm happy to jump onto Slack w/you if you'd like - our Slack URL is [readysetcommunity.slack.com](https://join.slack.com/t/readysetcommunity/shared_invite/zt-2272gtiz4-0024xeRJUPGWlRETQrGkFw) and I'm [@Andy Glover](https://readysetcommunity.slack.com/team/U05L423MPPZ).
