### ISSUE TITLE
Error Trying to Compile on Ubuntu

### ISSUE THREAD

**Issue by eni9889** [readysettech/readyset#878]
I am following the instruction to compile and getting this error:

![CleanShot 2023-11-09 at 09 02 58@2x](https://github.com/readysettech/readyset/assets/360222/80036df9-3ae5-4e24-b5b4-541be2ff715b)

**Comment by jasobrown-rs** [comment]
It looks like it's failing at the binary linking stage. What command did you use to compile?

Also, you  might need some system packages, like

sudo apt install -y build-essential libssl-dev pkg-config llvm clang liblz4-dev

**Comment by jasobrown-rs** [comment]
Also, i looks like the process was ended via `(signal: 9, SIGKILL: kill)`. Did you cancel the build?

**Comment by jasobrown-rs** [comment]
Hmm, maybe you need a larger build machine, as maybe the linux OOM killer is terminating the readyset build during the link stage. How large is that instance you are using? linking, in general, uses a lot of memory, and ReadySet is a fairly large app

**Comment by eni9889** [comment]
They might be the issue this is a fairly small instance I believe 1 CPU and 2 GB ram. That actually leads me to my next question, what are the recommended system specs. Also can the binary be compiled for arm64? @jasobrown-rs

**Comment by jasobrown-rs** [comment]
> what are the recommended system specs?
Hmm, good question. I don't think we have real specs for build systems, per se (at least that I know if). fwiw, i've used a `c6a.xlarge` for some testing, and compilation was successful.

wrt aarch64/arm64: we have a known problem in the rocksdb wrapper library currently, so it probably does not compile yet. Are you targeting something like graviton instances?

**Comment by jasobrown-rs** [comment]
@ronh-rs any opinions on build instance sizes?

**Comment by eni9889** [comment]
@jasobrown-rs I would like to use gravitron instances yea. Would save like 20% on cost which would be nice

**Comment by eni9889** [comment]
@jasobrown-rs I am now getting this error: 

![CleanShot 2023-11-10 at 13 30 25@2x](https://github.com/readysettech/readyset/assets/360222/01891e77-7512-4716-80c9-a7d1db91f5dd)

I followed the instructions here https://docs.readyset.io/reference/tls

**Comment by jasobrown-rs** [comment]
Note: this conversation migrated over to the ReadySet community slack: https://readysetcommunity.slack.com/archives/C03CM39SY3T/p1699642059683359.
