### ISSUE TITLE
Dual stack binding

### ISSUE THREAD

**Issue by Milo123459** [readysettech/readyset#923]
**Is your feature request related to a problem? Please describe.**=

Currently, ReadySet can only serve on `0.0.0.0` and `[::1]`. PostgreSQL in contrast serves on `0.0.0.0` and `[::]`

When making a template for https://railway.app/, apps need to support dual stack binding on the aforementioned addresses to allow communication between services. This would allow ReadySet to do that.

**Describe the solution you'd like**

Support `IPv4` and `IPv6` dual stack binding in ReadySet

**Describe alternatives you've considered**

N/A

**Additional context**

**Comment by lukoktonos** [comment]
After some debugging, we were able to get ReadySet working with in dual-stack by specifying `--address "[::]:5433"`. This allows connecting to readyset with either an ipv6 or an ipv4 address, e.g. `127.0.0.1:5433` or `[::1]:5433`
