### ISSUE TITLE
Query Support Checker Tool

### ISSUE THREAD

**Issue by lukoktonos** [readysettech/readyset#938]
**Description**

Our current way of checking if a query is supported or not involves standing up ReadySet, creating the tables for the query, and then attempting to create a cache for the query.

It would be nifty if there were a lightweight tool that used the same logic internally to do a dry run, but didn't require someone to fully set up ReadySet. We could maybe even avoid creating the tables for the query by deducing the schema needed and creating it on the fly, though that may involve making some assumptions about data types and end up being more work than it's worth vs just providing a way for users to provide the schemas along with the queries.

The tool could be hosted as a server and respond to query-supported requests, or could potentially (and here's the wild idea part) even be compiled to something like web-assembly and run client-side in the browser.

Note: This is more of a hackathon idea/wild idea that may be fun to implement than something I think we need immediately.
**
Change in user-visible behavior**

**Requires documentation change**

**Comment by gvsg-rs** [comment]
We will revive this in the near future.
