### ISSUE TITLE
Document using Railway w/ReadySet

### ISSUE THREAD

**Issue by aglover** [readysettech/readyset#941]
Add Railway starting guide to the docs

https://railway.app/template/wr1OLZ

**Comment by gvsg-rs** [comment]
We may want to create a community contribution section, and document this under there.

**Comment by Milo123459** [comment]
yeah, i think that could potentially be a good idea so that other one click deployment solutions could be advertised as well :)

**Comment by aglover** [comment]
[This PR](https://github.com/readysettech/docs/pull/117) adds Railway - we can rework things into a community section later as for now I've added this as an install option.

**Comment by aglover** [comment]
Thank you again @Milo123459!!
