### ISSUE TITLE
JIT compiled code for efficient fused filter evaluation operation

### ISSUE THREAD

**Issue by VladRodionov** [readysettech/readyset#972]
**Description**

Filter operation evaluation uses generic evaluator code which is sub-optimal from performance point of view due to excessive code branching and excessive number of function calls. Consider JIT approach to dynamical generate evaluation code for particular type of fused filter see [REA-3916](https://linear.app/readyset/issue/REA-3916).

**Change in user-visible behavior**

No

**Requires documentation change**

No

**Comment by gvsg-rs** [comment]
Deprioritized for now.
