### ISSUE TITLE
Re-evaluate whether caches should have names

### ISSUE THREAD

**Issue by ethan-readyset** [readysettech/readyset#985]
**Description**

Currently, caches can optionally be created with names via `CREATE CACHE <name> FROM <query or query ID>`. If they are created without a name, the query ID is used as the name. This query name is the why queries are referenced in the expression registry on the server, which is the source of truth for what caches exist. This has the unfortunate downside that if a cache is created with a name, there is no way to reference that cache with the query ID in `DROP CACHE` invocations. This is particularly confusing because `SHOW CACHES` supports filtering by the **query ID and not the name** via `SHOW CACHES WHERE query_id = <query ID>`.

We should re-evaluate whether there is utility in allowing users to create caches with names. On one hand, `CREATE VIEW` and `CREATE MATERIALIZED VIEW` in Postgres require names — there may be a world in which we *require* users to specify names when creating caches. On the other hand, if a user has many cached queries, it may be cumbersome to add names to every cache. It would simplify the user experience and the code base to either require names or do away with them entirely.

If we choose to keep both, we should do some work to disambiguate the concepts in our code base using types because at the moment, the terms are used interchangeably in some areas and distinctively in other areas, which makes some logic error prone and difficult to understand.

This is related to [REA-3937](https://linear.app/readyset/issue/REA-3937/query-id-is-treated-as-an-identifier-in-some-sql-extensions-and-a) in that both names and query IDs are currently treated as identifiers as opposed to strings, which is how Postgres and MySQL handle the names of tables/views. However, Postgres query IDs are `bigint`s, since they are hashes. In my opinion, it is a bit confusing that our auto-generated query IDs are identifiers (and as [REA-3937](https://linear.app/readyset/issue/REA-3937/query-id-is-treated-as-an-identifier-in-some-sql-extensions-and-a) explains, we treat query IDs as identifiers in some places and strings in other places).

**Change in user-visible behavior**

Yes

**Requires documentation change**

Yes

**Comment by gvsg-rs** [comment]
Looks like the "name" is being used by Cloud v2.

**Comment by gvsg-rs** [comment]
@ethan-readyset @tbjuhasz - can you please sync on this?

**Comment by gvsg-rs** [comment]
@ethan-readyset - Please review if this ticket continues to be relevant. 

Cloud requirement: Query names must be consistent across machines. (The same query should always result in the same id.)

@tbjuhasz - please provide more context about cloud requirements.
