### ISSUE TITLE
Make non-blocking reads the default

### ISSUE THREAD

**Issue by ethan-readyset** [readysettech/readyset#997]
**Description**

Currently, when a query encounters a hole in a reader map, the query blocks until the upquery finishes. For "pathological" queries whose upqueries currently take a very long time to complete, this behavior would cause substantially-degraded performance from the client's perspective. We already support a "non-blocking reads" mode, where queries don't wait for upqueries to complete and instead proxy upstream in the meantime, but it is disabled by default.

We should consider making this the default behavior, since it substantially lowers the chance that a pathological query severely impacts query latency as measured from the client's perspective.

**Change in user-visible behavior**

Yes

**Requires documentation change**

Yes

**Comment by lukoktonos** [comment]
Done in [https://gerrit.readyset.name/c/readyset/+/7204](https://gerrit.readyset.name/c/readyset/+/7204) [https://github.com/readysettech/readyset/commit/6ec10d446430560b2687561e836315ea12e15308](https://github.com/readysettech/readyset/commit/6ec10d446430560b2687561e836315ea12e15308)
